#!/usr/bin/env python3
"""
generate_mask_pngs.py

Creates mask PNG files to match the existing pre/post-contrast slices
generated by slicing_preprocessing.py. This ensures all precontrast images
have corresponding mask files with identical naming.
"""

import os
import numpy as np
import nibabel as nib
from PIL import Image
import pandas as pd
from tqdm import tqdm
import argparse
import glob

def create_mask_pngs_for_slices(segmentations_dir, output_base_dir, group_type, split):
    """
    Create mask PNGs for all extracted slices in a given group and split.
    
    Args:
        segmentations_dir: Directory containing expert segmentation NIfTI files
        output_base_dir: Base directory where slices are stored
        group_type: 'bilateral' or 'unilateral'
        split: 'train' or 'test'
    """
    
    # Get all precontrast files to understand what masks we need
    precontrast_dir = os.path.join(output_base_dir, f"{group_type}_slices", split, "precontrast")
    precontrast_files = [f for f in os.listdir(precontrast_dir) if f.endswith('.png')]
    
    print(f"Processing {group_type}/{split}: {len(precontrast_files)} precontrast slices")
    
    # Parse filenames to get patient IDs and slice indices
    file_info = []
    for filename in precontrast_files:
        try:
            base_name = filename.replace('.png', '')
            parts = base_name.split('_slice')
            
            if len(parts) != 2:
                print(f"Warning: Could not parse filename {filename}")
                continue
                
            patient_id = parts[0]
            slice_index = int(parts[1])
            
            file_info.append({
                'filename': filename,
                'patient_id': patient_id,
                'slice_index': slice_index
            })
        except Exception as e:
            print(f"Error parsing filename {filename}: {e}")
            continue
    
    # Create output directory for masks
    mask_output_dir = os.path.join(output_base_dir, f"{group_type}_slices", split, "masks")
    os.makedirs(mask_output_dir, exist_ok=True)
    
    from collections import defaultdict
    patient_files = defaultdict(list)
    for info in file_info:
        patient_files[info['patient_id']].append(info)
    
    # Process each patient
    success_count = 0
    fail_count = 0
    
    for patient_id, slices_info in tqdm(patient_files.items(), desc=f"Processing {group_type}/{split} patients"):
        # segmentation file for this patient
        seg_patterns = [
            os.path.join(segmentations_dir, f"{patient_id}.nii.gz"),
            os.path.join(segmentations_dir, f"{patient_id}_*.nii.gz"),
            os.path.join(segmentations_dir, f"*{patient_id}*.nii.gz")
        ]
        
        seg_path = None
        for pattern in seg_patterns:
            matches = glob.glob(pattern)
            if matches:
                seg_path = matches[0]
                break
        
        if seg_path is None or not os.path.exists(seg_path):
            print(f"Warning: Could not find segmentation file for patient {patient_id}")
            fail_count += len(slices_info)
            continue
        
        try:
            # Load the segmentation volume
            seg_img = nib.load(seg_path)
            seg_data = seg_img.get_fdata()
            
            # Generate masks for each slice
            for slice_info in slices_info:
                slice_idx = slice_info['slice_index']
                
                if len(seg_data.shape) == 3:
                    slice_data = seg_data[:, :, slice_idx]
                else: 
                    slice_data = seg_data[:, :, slice_idx, 0]
                
                binary_mask = (slice_data > 0).astype(np.uint8) * 255
      =
                mask_img = Image.fromarray(binary_mask, mode='L')
                
                #same filename as precontrast but with _mask suffix
                mask_filename = slice_info['filename'].replace('.png', '_mask.png')
                mask_output_path = os.path.join(mask_output_dir, mask_filename)
                
                mask_img.save(mask_output_path)
                success_count += 1
                
        except Exception as e:
            print(f"Error processing patient {patient_id}: {e}")
            fail_count += len(slices_info)
    
    return success_count, fail_count

def verify_mask_coverage(base_dir, group_type, split): 
    precontrast_dir = os.path.join(base_dir, f"{group_type}_slices", split, "precontrast")
    mask_dir = os.path.join(base_dir, f"{group_type}_slices", split, "masks")
    
    if not os.path.exists(mask_dir):
        print(f"Mask directory does not exist: {mask_dir}")
        return False
    
    pre_files = sorted([f for f in os.listdir(precontrast_dir) if f.endswith(".png")])
    mask_files = sorted([f for f in os.listdir(mask_dir) if f.endswith("_mask.png")])
    
    # Convert pre files to expected mask filenames
    expected_mask_files = set()
    for pre_file in pre_files:
        mask_file = pre_file.replace('.png', '_mask.png')
        expected_mask_files.add(mask_file)
    
    actual_mask_files = set(mask_files)
    
    # Check for missing masks
    missing_masks = expected_mask_files - actual_mask_files
    extra_masks = actual_mask_files - expected_mask_files
    
    print(f"\n Verification for {group_type}/{split}:")
    print(f"Total precontrast images: {len(pre_files)}")
    print(f"Total masks: {len(mask_files)}")
    print(f"Missing masks: {len(missing_masks)}")
    print(f"Extra masks: {len(extra_masks)}")
    
    if missing_masks:
        print("\nFirst 10 missing masks:")
        for f in list(missing_masks)[:10]:
            print(f"  - {f}")
        if len(missing_masks) > 10:
            print(f"  ... and {len(missing_masks) - 10} more")
    
    if extra_masks:
        print("\nFirst 10 extra masks:")
        for f in list(extra_masks)[:10]:
            print(f"  - {f}")
        if len(extra_masks) > 10:
            print(f"  ... and {len(extra_masks) - 10} more")
    
    return len(missing_masks) == 0

def main():
    parser = argparse.ArgumentParser(description='Generate mask PNGs for existing preprocessed slices')
    parser.add_argument('--segmentations_dir', type=str, required=True,
                       help='Directory containing expert segmentation NIfTI files')
    parser.add_argument('--output_base_dir', type=str, default=".",
                       help='Base directory where sliced images are stored')
    parser.add_argument('--verify', action='store_true',
                       help='Verify mask coverage after generation')
    
    args = parser.parse_args()
    
    print("Starting mask PNG generation...")
    print(f"Segmentations directory: {args.segmentations_dir}")
    print(f"Output base directory: {args.output_base_dir}")
    
    # Process all groups and splits
    groups = ['bilateral', 'unilateral']
    splits = ['train', 'test']
    
    total_success = 0
    total_fail = 0
    
    for group_type in groups:
        for split in splits:
            print(f"\n{'='*50}")
            print(f"Processing {group_type}/{split}")
            print(f"{'='*50}")
            
            success, fail = create_mask_pngs_for_slices(
                args.segmentations_dir, args.output_base_dir, group_type, split
            )
            
            total_success += success
            total_fail += fail
            
            print(f"Successful: {success}")
            print(f"Failed: {fail}")
    
    print(f"\n{'='*50}")
    print("Overall Results:")
    print(f"{'='*50}")
    print(f"Total successful: {total_success}")
    print(f"Total failed: {total_fail}")
        # Verification if requested

if __name__ == "__main__":
    main()
